#!/bin/bash

commit_message=$(cat "$1")

team_info="Nous sommes l'équipe 420, composée de Antoine Mourlot, Lubin, Théodore, Hugo Charles et pierre"
new_commit_message="$commit_message $team_info"

current_datetime=$(date "+ %Y-%m-%d %H:%M:%S")

new_commit_message="$new_commit_message $current_datetime"

echo "$new_commit_message" > "$1"
